fix integrationTests.yaml to properly use repo env vars

diff --git a/.github/workflows/integrationTests.yaml b/.github/workflows/integrationTests.yaml
--- a/.github/workflows/integrationTests.yaml
+++ b/.github/workflows/integrationTests.yaml
@@ -46,10 +46,11 @@ jobs:
             - name: Run integration tests
               env:
                   OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
+              if: ${{ env.OPENAI_API_KEY != '' }}
+              run: pnpm run integrationTests
+
+            - name: Skip integration tests
+              if: ${{ env.OPENAI_API_KEY == '' }}
               run: |
-                  if [ -z "$OPENAI_API_KEY" ]; then
-                    echo "Skipping integration tests due to missing required API keys"
-                    exit 1
-                  else
-                    pnpm run integrationTests
-                  fi
+                  echo "Skipping integration tests due to missing required API keys"
+                  exit 1
